version: "3.0"

services:
  db:
    image: mysql:8.0.34
    platform: linux/amd64
    container_name: mysql-container
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventory
      MYSQL_USERNAME: root
      MYSQL_HOST: localhost
    volumes:
      - ./database/config/my.cnf:/etc/mysql/conf.d/my.cnf